# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, List, Optional, Tuple

import pydantic

_BaseModel = pydantic.BaseModel

_isBaseModel = _BaseModel.__instancecheck__

_dict_type = dict


# Flattens dicts to be of the form {"key[subkey][subkey2]": value} where value is not a dict
def traverse_query_dict(dict_flat: Dict[str, Any], key_prefix: Optional[str] = None) -> List[Tuple[str, Any]]:
    result = []
    for k, v in dict_flat.items():
        key = f"{key_prefix}[{k}]" if key_prefix is not None else k
        if isinstance(v, dict):
            result.extend(traverse_query_dict(v, key))
        elif isinstance(v, list):
            for arr_v in v:
                if isinstance(arr_v, dict):
                    result.extend(traverse_query_dict(arr_v, key))
                else:
                    result.append((key, arr_v))
        else:
            result.append((key, v))
    return result


def single_query_encoder(query_key: str, query_value: Any) -> List[Tuple[str, Any]]:
    # Reduce attribute and isinstance lookups by binding type/functions
    BaseModel = _BaseModel
    isBaseModel = _isBaseModel
    dict_type = _dict_type

    # Use type() instead of isinstance if types are performance-limiting in this code path,
    # but here call isinstance only once where possible.
    if isBaseModel(query_value) or isinstance(query_value, dict_type):
        obj_dict = query_value.dict(by_alias=True) if isBaseModel(query_value) else query_value
        return traverse_query_dict(obj_dict, query_key)
    elif isinstance(query_value, list):
        # Preallocate output list if possible by summing subelement lengths, but list sizes are not known in advance,
        # so proceed with standard append/extend for minimal memory overhead
        result: List[Tuple[str, Any]] = []
        # Bind methods
        result_append = result.append
        result_extend = result.extend
        for value in query_value:
            if isBaseModel(value) or isinstance(value, dict_type):
                obj_dict = value.dict(by_alias=True) if isBaseModel(value) else value
                # Fast extend instead of creating an intermediate list
                result_extend(single_query_encoder(query_key, obj_dict))
            else:
                result_append((query_key, value))
        return result
    return [(query_key, query_value)]


def encode_query(query: Optional[Dict[str, Any]]) -> Optional[List[Tuple[str, Any]]]:
    if query is None:
        return None

    encoded_query = []
    # Bind for faster method access
    encoded_query_extend = encoded_query.extend
    for k, v in query.items():
        encoded_query_extend(single_query_encoder(k, v))
    return encoded_query
