# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, List, Optional, Tuple

import pydantic


# Flattens dicts to be of the form {"key[subkey][subkey2]": value} where value is not a dict
def traverse_query_dict(dict_flat: Dict[str, Any], key_prefix: Optional[str] = None) -> List[Tuple[str, Any]]:
    # Use local variable and local append for faster loop execution
    result_append = (result := []).append
    for k, v in dict_flat.items():
        key = f"{key_prefix}[{k}]" if key_prefix is not None else k
        if isinstance(v, dict):
            result.extend(traverse_query_dict(v, key))
        elif isinstance(v, list):
            for arr_v in v:
                if isinstance(arr_v, dict):
                    result.extend(traverse_query_dict(arr_v, key))
                else:
                    result_append((key, arr_v))
        else:
            result_append((key, v))
    return result


def single_query_encoder(query_key: str, query_value: Any) -> List[Tuple[str, Any]]:
    # Avoid redundant isinstance checks and function calls
    if isinstance(query_value, pydantic.BaseModel):
        obj_dict = query_value.dict(by_alias=True)
        return traverse_query_dict(obj_dict, query_key)
    elif isinstance(query_value, dict):
        return traverse_query_dict(query_value, query_key)
    elif isinstance(query_value, list):
        encoded_values_append = (encoded_values := []).append
        for value in query_value:
            if isinstance(value, pydantic.BaseModel):
                obj_dict = value.dict(by_alias=True)
                encoded_values.extend(single_query_encoder(query_key, obj_dict))
            elif isinstance(value, dict):
                encoded_values.extend(single_query_encoder(query_key, value))
            else:
                encoded_values_append((query_key, value))
        return encoded_values

    return [(query_key, query_value)]


def encode_query(query: Optional[Dict[str, Any]]) -> Optional[List[Tuple[str, Any]]]:
    if query is None:
        return None

    encoded_query = []
    for k, v in query.items():
        encoded_query.extend(single_query_encoder(k, v))
    return encoded_query
